#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/boasafra/boasafra /usr/bin/boasafra

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/boasafra.service ]; then
			rm /etc/systemd/system/boasafra.service /usr/lib/systemd/system/boasafra.service /usr/lib/systemd/user/boasafra.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/boasafra/files/systemd/boasafra.service /usr/lib/systemd/system/boasafra.service
		# try fix error in Ubuntu 18.04
		# Failed to reload boasafra.service: Unit boasafra.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/boasafra.service:10: Executable path is not absolute: pkill -f "boasafra --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/boasafra.service
		fi
		systemctl daemon-reload
		systemctl enable boasafra
		systemctl start boasafra
	fi
fi
