#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
		rm -f /usr/bin/boasafra
		
		if [ "systemd" == "${INITSYS}" ]; then

			systemctl stop boasafra || true
			systemctl disable boasafra || true
			rm /etc/systemd/system/boasafra.service /usr/lib/systemd/system/boasafra.service || true
			
			# workaround temp dev build between 1.1.9 and 1.2.0
			serverUser=$(ps -ef | grep -E 'boasafra +--server' | grep -v 'sudo ' | awk '{print $1}' | head -1)
			if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
			then
				systemctl --machine=${serverUser}@.host --user stop boasafra >/dev/null 2>&1 || true
			fi
			rm /usr/lib/systemd/user/boasafra.service >/dev/null 2>&1 || true
		fi
        ;;
esac

exit 0
